### ISSUE TITLE
Local caching

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#1]
[Service workers](https://developers.google.com/web/fundamentals/primers/service-workers/)

**Comment by mgmeedendorp** [comment]
Waarom niet [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)?

**Comment by Atema** [comment]
localStorage is niet heel optimaal voor grote hoeveelheden data volgens mij. Heb me niet enorm ingelezen over service workers, maar ze zouden ook op de achtergrond kunnen synchroniseren.
Nu ik wat verder lees, lijkt IndexedDB gebruiken ook wel wat; https://medium.com/dev-channel/offline-storage-for-progressive-web-apps-70d52695513c.

**Comment by Atema** [comment]
En: https://developers.google.com/web/ilt/pwa/live-data-in-the-service-worker#storing_data_with_indexeddb

**Comment by mgmeedendorp** [comment]
Hmm, het eerste voordeel van service workers is dat ze ook afbeeldingen op kunnen slaan, wat later handig is als we de foto's aan de expeditie pagina willen toevoegen. IDB klinkt inderdaad ook wel interessant, daar heb ik eigenlijk nog nooit van gehoord.

**Comment by mgmeedendorp** [comment]
Al geïmplementeerd
