### ISSUE TITLE
Japan route

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#11]
Ik heb nog wat locatie data van Japan liggen, is waarschijnlijk compleet nutteloos of moeilijk op te schonen omdat er geen GPS bereik is in de treinen

**Comment by mgmeedendorp** [comment]
Zie [deze](https://mmeedendorp.stackstorage.com/s/XEVxhl22qsAnsC8) link voor locatie data

**Comment by Atema** [comment]
> Zie [deze](https://mmeedendorp.stackstorage.com/s/XEVxhl22qsAnsC8) link voor locatie data

Alleen foto's? Of was dat het idee?

**Comment by mgmeedendorp** [comment]
Verkeerde map, oeps
Dit is de nieuwe:
[link](https://mmeedendorp.stackstorage.com/s/9Zpzmswwb91za2b)

**Comment by mgmeedendorp** [comment]
Aah, geen markdown support via email blijkbaar. Nou, het idee is duidelijk :P

**Comment by mgmeedendorp** [comment]
Hoe dan. Het ziet er nog goed uit ook 😮
