### ISSUE TITLE
Trip Medeo stadium etc. - Missende locatiedata (27.07.2018)

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#16]
@mgmeedendorp Heb jij misschien Google locatiedata?

**Comment by mgmeedendorp** [comment]
![Deze?](https://i.imgur.com/UykNrm6.jpg) Deze?

**Comment by Atema** [comment]
Ja, die

**Comment by mgmeedendorp** [comment]
[history-2018-07-28.kml.txt](https://github.com/Expeditie-Grensland/Website/files/2434270/history-2018-07-28.kml.txt)

Het is .KML, maar dat mag je niet uploaden naar github

**Comment by mgmeedendorp** [comment]
Het is trouwens de 28e, niet de 27e

**Comment by Atema** [comment]
![image](https://user-images.githubusercontent.com/774965/46311362-30ed8580-c5c2-11e8-9d6b-ad5a8e9950ba.png)
yay :)
