### ISSUE TITLE
Mapbox performance

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#18]
De kaart is (met Holter internet iig) iets waar ik bij elke pagina op moet wachten. De tiles worden niet offline gecached. Dit schijnt mogelijk te zijn met service workers, zie https://github.com/mapbox/mapbox-gl-js/issues/4326

Er wordt een voorbeeld bij genoemd, die op mijn telefoon en stuk sneller laad na de eerste keer

**Comment by Atema** [comment]
Yay voor service workers
  
  
  

  
  
  
  
  
>

**Comment by Atema** [comment]
Jammer dat ik morgen in het ziekenhuis lig...
  
  
  

  
  
  
  
  
>

**Comment by mgmeedendorp** [comment]
Ik ben hier gisteren en vandaag mee bezig geweest, maar ik krijg de types niet voor elkaar, er lijkt vrijwel geen ondersteuning voor te zijn in typescript, omdat het een experimental feature is. Zou jij hier misschien nog naar willen kijken? De service worker moet gecompiled worden naar een apart .js bestand wat de browser apart weer gaat downloaden. Ik heb het toegevoegd aan de gulp bestanden.

Het cachen is het makkelijkste via de Cache API, alleen beschikbaar voor service workers.

Resources over service workers:
[MDN | Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)
[MDN | Using Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)
[MDN | Cache Web API](https://developer.mozilla.org/en-US/docs/Web/API/Cache)

**Comment by mgmeedendorp** [comment]
Alle requests naar tiles.mapbox.com en api.mapbox.com worden nu gecached door de service worker (als gulp naar behoren werkt). Zie: f1ed2118549b1dc6663e9ea6d0efd8d9ced70984

Het cachen versnelt het laden van de pagina enorm op langzame internetverbindingen.

Ondanks het cachen duurt het nog steeds erg lang (soms > 10s) voordat de kaart voor het eerst getekend wordt, en in mijn ervaring blijft de kaart aardig langzaam. Voorbeelden van snellere kaarten die ik op andere websites tegenkom gebruiken dan ook veelal geen mapbox-gl-js, maar openlayers ([voorbeeld](https://www.mapbox.com/help/mapbox-with-openlayers/)) of mapquest ([voorbeeld met caching](https://zikes.website/)), die beide ook kunnen werken icm met mapbox vector tiles. 

Zie ook (https://github.com/mapbox/mapbox-gl-js/issues/3153)

Het lijkt me een goed idee om te kijken naar (snellere) alternatieven voor mapbox, helemaal omdat we nu nog niet zoveel met de kaart doen en nog makkelijk kunnen veranderen.

**Comment by mgmeedendorp** [comment]
Het is met openlayers ook mogelijk om de kaart als een globe weer te geven, wat ik persoonlijk ook heel mooi vind. Zie: [link](http://openlayers.org/ol-cesium/). Dan is het echter weer niet mogelijk om mapbox tiles te gebruiken :(

**Comment by mgmeedendorp** [comment]
Nadat ik - terwijl ik andere dingen moest doen - wat over kaarten gelezen heb lijkt me dit de mooiste oplossing: 

De kaart layer van Mapbox, met de API van OpenLayers, getekend op een globe met Cesium-OL ([voorbeeld](https://cesiumjs.org/), selecteer rechtsboven mapbox layer) 

Het is ook mogelijk om een terrain layer toe te voegen, waardoor bergen en sommige gebouwen ook in relief komen.

@Atema, wat denk jij van dit hele verhaal?

**Comment by mgmeedendorp** [comment]
Andere opties zijn vrijwel onmogelijk met mapbox styles.

**Comment by mgmeedendorp** [comment]
Ik zie dat wij mapbox-gl versie 0.51.2 gebruiken, terwijl onderhand 1.3.1 al uit is. Met wat geluk helpt dit in de performance. 

Ik lees in de [changelog](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md) ook dat er standaard tile caching in mapbox zit, wat onze service worker misschien wat overkill maakt. Hier moet ook naar worden gekeken.

**Comment by mgmeedendorp** [comment]
Na de links in de eerste comment van deze issue gelezen te hebben lijken service workers nog steeds een goede aanvulling op de default caching

**Comment by Atema** [comment]
Na d0d66efe1b134837ad1f47362d3a57bef292ca2f is het sneller
