### ISSUE TITLE
Frontend Supergave Kaart

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#23]
Volgens het design gespecificeerd in #7 

- Het verhaalmenu
  - [x] Titel
  - [x] Route lijnen
  - Verhaalelementen
    - [x] Locatie
    - [x] Tekst
    - [x] Foto('s)/video('s)
-  Kaart
  - Verhaalelementen op de route
    - [x] Locatie
    - [x] Tekst
    - [ ] Foto('s)/video('s)

**Comment by Atema** [comment]
![kaartpagina](https://user-images.githubusercontent.com/774965/48264507-0812a880-e42a-11e8-84e4-f23d9815ae5d.png)

**Comment by mgmeedendorp** [comment]
De frontend voor het verhaal met text en location elements is geimplementeerd in 43fd06f283dc49abd49df843a93f569238ad6650. Er is nog geen enkele integratie met de kaart.

**Comment by mgmeedendorp** [comment]
![image](https://user-images.githubusercontent.com/3658232/204655203-d5c60e56-b4a0-4f6f-a18e-6a25b6fb9df7.png)

b9d537eaa2f08aef5da3bde76c63efbd0559e665

Klikken op de cirkels in het verhaalmenu en op de kaart zoomt in op de desbetreffende cirkel. Afbeeldingsupport is nog volledig afwezig
