### ISSUE TITLE
Homepage werkend maken in safari 

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#29]

**Comment by Atema** [comment]
Wat is het probleem?

**Comment by mgmeedendorp** [comment]
Op zowel mobiel als desktop werken de pijlknoppen niet. Op desktop kun je
niet handmatig scrollen, op mobiel wel.

**Comment by mgmeedendorp** [comment]
Hetzelfde probleem bestaat in MS Edge
