### ISSUE TITLE
Zet de themakleur gelijk met de achtergrondkleur

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#30]
Ik zag net een website die de kleur van de notificatiebalk op Android veranderde, dat kunnen wij ook. Expeditieblauw lijkt me wel mooi

**Comment by Atema** [comment]
We hebben een officiële Expeditieblauw?

**Comment by mgmeedendorp** [comment]
https://stackoverflow.com/a/26960753

**Comment by mgmeedendorp** [comment]
Theme color is al in 2020 (09a66301b8200d07ee000bdccbf25ef50748f81d) toegevoegd.
