### ISSUE TITLE
Admin pagina woordenboek, citaten en punt'n

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#31]
Een admin pagina om nieuwe woorden, citaten en punt'n toe te voegen aan de website

**Comment by Atema** [comment]
Voor wie zouden deze toegankelijk moeten zijn?

**Comment by mgmeedendorp** [comment]
Alleen voor de pieljonkjes denk ik, het is een stuk meer werk om zo'n form compleet idiot-proof te maken

**Comment by mgmeedendorp** [comment]
Kan deze nu niet dicht?

**Comment by mgmeedendorp** [comment]
Iétsje meer idiot-proof zou wel mooi zijn. Hoe zijn 'uploaden' en 'toevoegen' twee verschillende acties met beide een blauwe knop die schreeuwt: 'ik ben het meest belangrijk'?

Bijgevoegd wat gebeurt als je op 'toevoegen' klikt zonder een bestand te selecteren en dit (waarschijnlijk niet-bestaande) bestand daarna weer uit de lijst probeert te verwijderen. Hij lijkt wel weg te zijn uit de database want hij staat niet meer in de lijst.

![Screenshot from 2019-12-16 15-14-31](https://user-images.githubusercontent.com/3658232/70913696-ceda3e00-2016-11ea-96bf-37ae2f2fee95.png)

(De foutmeldingen zijn wel super)

**Comment by Atema** [comment]
Idioten hebben geen toegang tot deze pagina :)
Die toevoegen is juist bedoeld dat je geen bestand selecteert, zodat je deze via ftp ofzo kan uploaden (idd niet helemaal duidelijk in de interface)
