### ISSUE TITLE
Dev build pipeline sneller maken

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#33]
Ik heb vanavond geprobeerd de watch build pipeline sneller te maken maar dat is niet gelukt. Het systeem werkt goed, maar het is te langzaam om productief aan de website te werken. Er zijn meerdere verbeterpunten.

- [x] `gulp watch` heeft bij een verandering van client-side code bijna een hele minuut nodig tussen 'starting bundling <file>' en 'finished bundling <file>'.

- [x] Als er een bestand veranderd worden alle client bundles opnieuw gemaakt terwijl dat vrijwel nooit nodig is.

In de [gulp documentatie](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md) staat een voorbeeld voor een browserify + watchify setup waar de build time na de eerste keer in de orde van 100ms zou moeten zijn voor een project waar de eerste build ~30s duurt. Het lijkt me dus dat voor ons zoiets ook haalbaar moet zijn.

@Atema Heb jij hier ideeën over? Een korte uitleg over hoe de build pipeline in elkaar steekt zou ook mooi zijn.

**Comment by mgmeedendorp** [comment]
Ik ga binnenkort proberen om een aparte dev pipeline op te zetten op basis van microsoft/TypeScript-Node-Starter

**Comment by Atema** [comment]
Nog steeds niet donders snel, maar (bij mij iig) terug naar enkele seconden door niet langer builden alle bundels bij het veranderen van één bestand.

**Comment by mgmeedendorp** [comment]
Bij mij is de build tijd terug naar 10 seconden voor wijzigingen aan de client 🎉 

Nu weer verder met #23!
