### ISSUE TITLE
Route spitsbergen 1.0

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#36]
Uit mijn locatiegeschiedenis en foto's kan ik vast nog een half-delegelijke route halen van expeditie spitsbergen 1.0

**Comment by Atema** [comment]
Vanuit je foto's:
[Spitsbergen 1.0.gpx.zip](https://github.com/Expeditie-Grensland/Website/files/3881801/Spitsbergen.1.0.gpx.zip)

**Comment by mgmeedendorp** [comment]
Gelukt met de data uit google maps timeline export
