### ISSUE TITLE
Duplicate locaties

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#38]
Wel op te lossen met een unique index, maar daarvoor moeten eerst de huidige duplicaten eruit worden gehaald.

**Comment by mgmeedendorp** [comment]
Duplicate op basis waarvan? Lat/lon?

**Comment by Atema** [comment]
Nee, algeheel, dus gewoon dezelfde locatie twee keer geüpload -> zou niet moeten kunnen

**Comment by mgmeedendorp** [comment]
In welke situatie hebben we hier last van?
