### ISSUE TITLE
Optimize transferring locations over socket

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#4]
At the moment, long and useless information is sent (e.g. long `route`, `_id`, and `node` parameters). This could be optimised to improve loading speeds.

**Comment by mgmeedendorp** [comment]
Ik ben er al mee bezig geweest, maar de code is onderhand zo veel veranderd dat ik overnieuw moet beginnen. Ik heb er de komende tijd sowieso geen tijd voor ivm uni

**Comment by Atema** [comment]
Aii, ja, ik was al bang dat ik iets kapot zou maken. Je kunt het wel 
naar een nieuwe branch pushen, dan kijk ik ernaar. Ik zit toch nog wel 
even stil.

------ Original Message ------

**Comment by Atema** [comment]
Het zou nog sneller moeten (caching?), maar het is stukken
beter dan het was
