### ISSUE TITLE
Verschil uploaden en toevoegen op admin bestanden duidelijker maken

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#40]
Zie @mgmeedendorp in #31

**Comment by Atema** [comment]
Ik denk een visuele scheiding tussen de twee forms, en een korte uitleg bij de 'toevoegen' form

**Comment by mgmeedendorp** [comment]
Lijkt me prima

**Comment by mgmeedendorp** [comment]
Gefixed in 4c83266625f4fa0af85f716f32486340a62739cb
