### ISSUE TITLE
Verzoek tot aanpassing 'Regisseur'

### ISSUE THREAD

**Issue by DHBlaauw** [Expeditie-Grensland/Website#48]
Geachte gebroeders Piel,

Hierbij een verzoek om het woord 'Regisseur' op de afzonderlijke expeditiepagina's gelieve aan te passen naar 'Filmmonteur' or 'Editor'. Dit denkt m.i. de lading beter dan 'regisseur', aangezien de film niet gescript is.

Bij voorbaat dank.

Mvh, Diederik

(Einde bericht).

**Comment by Atema** [comment]
Wordt filmmonteur wel gebruikt in Nederland?   
  

  

  

  
  
  
  
  
>

**Comment by mgmeedendorp** [comment]
https://nl.wikipedia.org/wiki/Editor_(beroep)
Lijkt t wel

**Comment by Atema** [comment]
Ik zou er editor van maken

------ Original Message ------

**Comment by Atema** [comment]
Of "montage"

------ Original Message ------
From: "Martijn Atema" <martijn@atema.one>
To: "Expeditie-Grensland/Website" 
<reply@reply.github.com>
Sent: 19/05/2020 15:25:40
Subject: Re: [Expeditie-Grensland/Website] Verzoek tot aanpassing 
'Regisseur' (#48)

**Comment by mgmeedendorp** [comment]
We gaan het zien
https://www.strawpoll.me/20100335/r

**Comment by Atema** [comment]
Ik haat democratie :(
