### ISSUE TITLE
Geen expeditie-logo Safari

### ISSUE THREAD

**Issue by kiyoomogi** [Expeditie-Grensland/Website#64]
De expeditie Grensland favicon op Safari is een zwart blokje i.p.v. het logo. 

<img width="123" alt="image" src="https://user-images.githubusercontent.com/101344020/177654245-5e36d3be-78f5-4503-820a-2a6bb71844d4.png">

**Comment by mgmeedendorp** [comment]
Ik kan het probleem niet reproduceren. Waar in safari en op welk apparaat komt dit voor?

**Comment by kiyoomogi** [comment]
In de zoekbar verschijnt het logo wel, maar het icoontje in de tab is een zwart blokje. Op Macbook.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/101344020/204673418-d2f9e250-8504-4c03-b72b-491bad2bfc8d.png">

<img width="133" alt="image" src="https://user-images.githubusercontent.com/101344020/204673454-2df6bbd6-d862-4670-aa11-edf7adf98d25.png">

**Comment by mgmeedendorp** [comment]
Ik kan het bij gebrek aan een macbook niet goed testen. We staan open voor een pull request.
