### ISSUE TITLE
Omslagfoto Expeditie Poolse Tatra’s

### ISSUE THREAD

**Issue by DHBlaauw** [Expeditie-Grensland/Website#65]
Omslagfoto P. Tatra’s wijzigen in droneshot foto van ons houten huisje (met sauna en hottub in beeld). Of een beter (passender) alternatief.

**Comment by mgmeedendorp** [comment]
Had je een foto in gedachten?

**Comment by Atema** [comment]
Eindelijk maar toch :)

**Comment by DHBlaauw** [comment]
Een donders schiere datcha 🙏🏼
