### ISSUE TITLE
Video afspeelfout webstee

### ISSUE THREAD

**Issue by DHBlaauw** [Expeditie-Grensland/Website#66]
Geachte lieden van de GithubCie,

Via deze digitale weg wil ik gaarne blijk maken van een fout op expeditiegrensland.nl.
Ik krijg bij het drukken op de play-knop een icoontje te zien dat afspelen niet mogelijk is (zie bijlage hieronder). Dit bij zowel expeditie terug naar de -stans als bij expeditie Canada (heb de rest niet gecheckt). Bij voorbaat dank en groeten.

https://github.com/Expeditie-Grensland/Website/assets/65603774/f1983770-3cac-4d7d-8490-31be7abf7a64

**Comment by mgmeedendorp** [comment]
Dit probleem doet zich ook voor op windows. Alle expeditiefilms zijn niet meer te bekijken

**Comment by mgmeedendorp** [comment]
Het lijkt erop dat alle film-gerelateerde bestanden niet meer te vinden zijn op de url waar ze eerder waren. (bijv. https://expeditiegrensland.nl/media/vesteralen/index.m3u8). Deze resources geven allemaal een 404 response met de code "NoSuchKey".

Het lijkt erop dat ik geen toegang meer heb tot de database en de /mnt/expeditiegrensland-media map op de server lijkt voor mij leeg te zijn dus ik kan verder niet zien wat het probleem is.

Misschien dat de wijziging in 5222cf531e14f3f4d5f3e301cdad10a698db4d9f wel al toegepast is op de database maar nog niet op de release server draait?

Mocht het filmmateriaal per ongeluk verwijderd zijn, dan staan alle hls-bestanden op de Expeditie Big Data (onder ExpeditieNaam/Beeldmateriaal/.webite-hls)

**Comment by Atema** [comment]
Mijn fout 😅 ik heb de bestanden wat heen en weer gegooid, maar is niet helemaal goed gegaan. @mgmeedendorp als je bij de db kan, kun je de movieHlsDir met "old/" prefixen en zou het weer moeten werken (de db en gebruiker heten nu expeditiegrensland ipv expeditie-grensland)

**Comment by mgmeedendorp** [comment]
Ah die gebruikersnaam was het probleem. Ik kan er weer bij, top! 

De movieHlsDir kolom lijkt nog niet te bestaan in de database omdat commit 5222cf531e14f3f4d5f3e301cdad10a698db4d9f nog niet in release draait. Kan ik de master branch in de release branch mergen om dat te fixen of is die nog niet af?

**Comment by Atema** [comment]
Ja, ga je gang :)

**Comment by mgmeedendorp** [comment]
Top, ik heb de wijzigingen naar release gemerged en de database aangepast zoals je suggereerde. Alle films lijken het weer te doen 👌. Thanks Martijn! 

Ik zal direct ook de locatiegegevens van de laatste expeditie updaten met de gecorrigeerde GPX bestanden.
