### ISSUE TITLE
Achtergrond voor Expeditie Saltfjellet

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#68]
Ik had nog een paar foto's staan, of anders moet er even iets uit een video gehaald worden. Geef de voorkeur maar door :) @DHBlaauw

Optie 1:
![20230718_165044](https://github.com/Expeditie-Grensland/Website/assets/774965/666f1315-27c8-4b94-a9ba-6e71591f8bb2)
![2024-01-11 20 50 08 wsl localhost - Expeditie Grensland - Achtergrond Test - 09cee5d50f12](https://github.com/Expeditie-Grensland/Website/assets/774965/8636d7f5-fba3-43c1-8987-c0a279a929e7)

Optie 2:
![IMG_0808](https://github.com/Expeditie-Grensland/Website/assets/774965/b57031e9-bbed-47dd-9277-cfcb1cd83878)
![2024-01-11 20 51 21 wsl localhost - Expeditie Grensland - Achtergrond Test - 20dd1a0f25a5](https://github.com/Expeditie-Grensland/Website/assets/774965/8a18cc69-9475-4b6b-99eb-8560f0b2ab31)

Optie 3:
![IMG_0870](https://github.com/Expeditie-Grensland/Website/assets/774965/3adf2bfe-7cfe-4481-8cb3-dd4f8d350b53)
![2024-01-11 20 52 26 wsl localhost - Expeditie Grensland - Achtergrond Test - c40505c918c2](https://github.com/Expeditie-Grensland/Website/assets/774965/01194c02-16e3-4f32-a7e7-ef0b8125af99)

Optie 4:
![IMG_0887](https://github.com/Expeditie-Grensland/Website/assets/774965/e307480d-da91-47a7-9a7f-d42a88f0e613)
![2024-01-11 20 53 55 wsl localhost - Expeditie Grensland - Achtergrond Test - 64f5a10781cb](https://github.com/Expeditie-Grensland/Website/assets/774965/e1e3de43-62f5-438e-8a1f-88635f2ff325)

**Comment by DHBlaauw** [comment]
Goed werk. Ik vind dat blauwe water van optie 1 wel heel gaaf eruit zien. 

Eventueel een beter alternatief zou een screenshot uit de dronebeelden zijn, met de hytte, het ijsmeertje, wat sneeuw en rotsen/bergen erop. Suggesties tussen 14:28 - 14:32. Weet niet of dat er schier uit ziet.
