### ISSUE TITLE
Proposals: Expeditie Kaart

### ISSUE THREAD

**Issue by Atema** [Expeditie-Grensland/Website#7]
I have some ideas

**Comment by mgmeedendorp** [comment]
Gaat dit over de overview map die eerst op de main pagina stond, of over de layout van de expeditie pagina's? 

Voor die 2e heb ik namelijk ook een aantal ideeën die ik wel kan delen

**Comment by Atema** [comment]
Zeg maar de overview kaart die eerst op de hoofdpagina stond maar dan op aparte expeditie pagina's in combinatie met de rest.

Dus stuur maar op!

**Comment by mgmeedendorp** [comment]
Voor de expeditie pagina heb ik eigenlijk twee ideeën liggen; eentje die de focus meer op de kaart legt en eentje die de focus legt bij de foto's en logboek entries (died heeft de afgelopen 2 jaar verhaaltjes bijgehouden onderweg). 

Bij beide designs staan 2 items centraal: de kaart en de timeline.

#### Kaart 

De kaart is grotendeels wat we nu hebben, een kaart met een lijn voor de afgelegde route, één lijn voor elke groep mensen, ieder met een eigen kleur. Op een lijn zijn verschillende dingen zichtbaar: de 'places', foto's en logboek entries.

Een place is een plek waar we langere tijd op dezelfde plek zijn geweest, mogelijk meerdere keren. Dit kan een hotel, bezienswaardigheid of mogelijk een restaurant zijn. Deze wordt aangegeven door een stip op de lijn, misschien met informatie on click (moet uitgewerkt worden).

Een 'foto' kan bestaan uit een of meerdere foto's of videos die op de plaats waar ze gemaakt zijn op de kaart worden aangegeven door een cirkel met een thumbnail van de foto. Als erop geklikt wordt opent zich een popup met de foto's in een soort galerij.

Een logboek entry wordt net als een foto weergegeven, maar met miniatuur van de tekst (of een nummer (?)) als thumbnail. Als er foto's en logboek entries op dezelfde plek staan worden deze gecombineerd weergegeven in een galerij alsof de logboek entry een foto is.

#### Timeline

De timeline is waar het grootste verschil zit tussen de twee designs, dus de beschrijving is wat algemener. In het kort geeft de timeline exact dezelfde informatie weer als de routes op de kaart, maar in de tijd-dimensie in tegenstelling tot de lat/lon-dimensie van de kaart. Bij de timeline wordt ook datum/tijd informatie weergegeven, de datum en de tijd van elke entry (foto, logboek of place) wordt weergegeven. 

### Design 1

Dit idee is gefocust op het integreren van timeline met de kaart, onderstaande schets geeft een voorbeeld. Hier zie je de tijdlijn horizontaal bovenaan het scherm met de verschillende routes, en de kaart onderaan met de route erop geschetst.


![img_20180820_155130](https://user-images.githubusercontent.com/3658232/44348526-f3fa8300-a49a-11e8-97ca-ebf22ed8501c.jpg)

Hier zijn de kaart en de tijdlijn gelinkt aan elkaar, als je inzoomt op de kaart, wordt er ook ingezoomd op de tijdlijn en inzoomen op de tijdlijn zorgt ervoor dat ook de kaart inzoomt op het relevante deel van de route. De tijdlijn kan ook worden verschoven (misschien gescrolt) om de reis chronologisch weer te geven. 

![img_20180820_172533](https://user-images.githubusercontent.com/3658232/44350239-1db5a900-a49f-11e8-8d2d-857665556f13.jpg)


(ik hoop dat je het kunt lezen)

### Design 2

Design 2 is minder uitgewerkt en meer gefocust op het 'verhaal' van de reis dan op de route. Het is vooral gebaseerd op [deze supermooie website](https://tympanus.net/Development/StorytellingMap/) en de schets zegt eigenlijk alles.

![img_20180820_165229](https://user-images.githubusercontent.com/3658232/44350005-a6801500-a49e-11e8-9387-e4c8b7ff79e8.jpg)

**Comment by Atema** [comment]
Ik blijf die website wel heel gaaf vinden. Je zou het ook meer kunnen combineren met het eerste design, dat de timeline in plaats van horizontaal met thumbnails op de kaart, verticaal wordt weergegeven, waarbij de tekst en afbeeldingen naast de timeline staan. (Volgens mij ook zoals het in die schets staat?) Is wel weer lastiger te doen om een goede relatie te houden tussen scrolafstand en tijd op de kaart, omdat onze kaart veel gedetailleerder en met imperfecties (niet speciaal ervoor gemaakt, zoals die van IJsland) is.

**Comment by mgmeedendorp** [comment]
Yup, dat zijn ook mijn overwegingen. Ik ben persoonlijk meer fan van het eerste voorstel omdat dat meer data-gericht is en ik ben bang dat het tweede voorstel heel snel lelijk gaat lijken met veel foto's of lange stukken zonder tekst. Eigenlijk wil ik sowieso de interactie tussen de timeline en de map op een of andere manier behouden. Ik ga er nog een nachtje over slapen

**Comment by mgmeedendorp** [comment]
Nog iets: kijkend naar de expeditie pagina's die we nu hebben, zou een simpele eerste stap voor het verbeteren van de 'leesbaarheid' van de kaart het aangeven van lange stukken geen GPS signaal zijn. Bijv in de metro in Japan. Mijn idee is dan om de 'onzekere' stukken van de route (met lange tijd geen locaties) met een stippellijn en evt half-doorzichtig weer te geven.

Volgens mij is dit redelijk goed te doen aan de client side, door meerdere lijnen met verschillende stijlen te tekenen op de kaart.

Een tweede onderscheid wat we in dezelfde categorie kunnen maken is het aangeven van gevlogen routes dmv de GPS hoogte (als die nauwkeurig genoeg is)

**Comment by mgmeedendorp** [comment]
We gaan voor design 2.

**Comment by mgmeedendorp** [comment]
Is geïmplementeerd als 'map stories' in 5fd7c155e587b240ef1955f42199c46f06af6b96
