### ISSUE TITLE
Nordkapp route

### ISSUE THREAD

**Issue by mgmeedendorp** [Expeditie-Grensland/Website#9]
Met de GPS locaties van de foto's en een beetje google maps-gokkerij moet het lukken om een benadering van onze noordkaap route te genereren voor de website.

**Comment by Atema** [comment]
Het hele Scandinavische stuk zou niet heel moeilijk moeten zijn...

**Comment by mgmeedendorp** [comment]
Als je dan toch bezig bent met nieuwe routes :P
[Hier](https://mmeedendorp.stackstorage.com/s/EWK7nRiGbuKaOtk) staan de ge-geotagde foto's van de Noordkaap. De foto's met als naam `IMG_nnnn.JPG` zijn van Diederik's iPhone, die hebben wel een geotag, de fotos genaamd `IMG_yyyymmdd_hhmmssuuu.jpg` zijn van mijn Motorola zonder GPS tags.
De video's hebben geen geotag

**Comment by mgmeedendorp** [comment]
Damn, da's best indrukwekkend nog van alleen de foto's 
Een evt. verbetering zou zijn door de punten aan elkaar te koppelen via de wegen
